---

- name: Add apt transport https
  apt:
    name: "apt-transport-https"

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repos }}"

- name: Install apt packages (from repo)
  apt:
    name: "{{ item }}"
  with_items: "{{ apt_pkgs }}"

- name: Install apt packages (from deb)
  apt:
    name: "{{ item }}"
  with_items: "{{ apt_debs }}"
