# "username" variable defined in the playbook
home: "/home/{{ username }}"
projects_folder: "{{ home }}/devel"
virtualenv_folder: "{{ home }}/.venvs"
profile_file: "{{ home }}/.profile"
nodejs_version: "10.x"
pip_package: python3-pip
virtualbox_install_dkms: yes
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} bionic {{ docker_apt_release_channel }}"
docker_install_compose: yes
ohmyzsh_plugins: debian docker git git-extras git-flow history ng node npm pip python sudo virtualenvwrapper
go_version: 1.10.4
GOPATH: "{{ home }}/go"
GOROOT: /usr/local/go
create_folders:
  - "{{ projects_folder }}"
  - "{{ projects_folder }}/work"
  - "{{ projects_folder }}/personal"
  - "{{ virtualenv_folder }}"
  - "{{ GOPATH }}"
apt_repo_keys:
  - https://packages.gitlab.com/runner/gitlab-runner/gpgkey
  - https://pkgs.tailscale.com/stable/ubuntu/eoan.gpg
  - https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg
apt_repos:
  # Add repo required in 20.04 for python3-pip
  # May be obsolete when geerlingguy/ansible-role-pip#12
  # is resolved
  - "deb http://archive.ubuntu.com/ubuntu focal universe"
  - "deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ bionic main"
  - "deb-src https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ bionic main"
  - "deb https://pkgs.tailscale.com/stable/ubuntu eoan main"
  - "deb https://download.zerotier.com/debian/bionic bionic main"
  - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
apt_pkgs:
  - bat
  - caffeine
  - curl
  - fswatch
  - g++
  - gcc
  - gitlab-runner
  - gnome-tweak-tool
  - jq
  - kafkacat
  - kubectl
  - mingw-w64
  - mtr-tiny
  - net-tools
  - openconnect
  - pass
  - plank
  - steam-installer
  - tailscale
  - ubuntu-restricted-extras
  - virtualbox
  - wget
  - youtube-dl
apt_debs:
  - https://zoom.us/client/latest/zoom_amd64.deb
  - https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
snap_pkgs:
  - code
  - dbeaver-ce
  - drawio
  - gitkraken
  - insomnia
  - rocketchat-desktop
  - spotify
pip_install_packages:
  - name: docker
  - name: virtualenvwrapper
users:
  - name: "{{ username }}"
    groups: "sudo, docker"
ohmyzsh_users:
  - username: "{{ username }}"
    usergroup: "{{ username }}"
    home: "{{ home }}"
config_contents:
  - name: virtualenvwrapper
    path: "{{ profile_file }}"
    block: |
      export VIRTUALENVWRAPPER_PYTHON=$(which python3)
      export WORKON_HOME={{ virtualenv_folder }}
      export PROJECT_HOME={{ projects_folder }}
  - name: golang
    path: "{{ profile_file }}"
    block: |
      export GOPATH={{ GOPATH }}
      export PATH=${PATH}:${GOPATH}/bin:{{ GOROOT }}/bin
