# "username" variable defined in the playbook
home: "/home/{{ username }}"
projects_folder: "{{ home }}/devel"
virtualenv_folder: "{{ home }}/.venvs"
profile_file: "{{ home }}/.profile"
nodejs_version: "10.x"
pip_package: python3-pip
virtualbox_install_dkms: yes
docker_install_compose: yes
ohmyzsh_plugins: debian docker git git-extras git-flow history ng node npm pip python sudo virtualenvwrapper
go_version: 1.10.4
GOPATH: "{{ home }}/go"
GOROOT: /usr/local/go
create_folders:
  - "{{ projects_folder }}"
  - "{{ virtualenv_folder }}"
  - "{{ GOPATH }}"
apt_repos:
  # Add repo required in 18.04 for python3-pip
  # May be obsolete when geerlingguy/ansible-role-pip#12
  # is resolved
  - "deb http://archive.ubuntu.com/ubuntu bionic universe"
  # Adapta theme ppa
  - "ppa:tista/adapta"
apt_pkgs:
  - adapta-gtk-theme
  - adapta-backgrounds
  - curl
  - g++
  - gcc
  - gnome-tweak-tool
  - ubuntu-restricted-extras
  - virtualbox
  - virtualbox-ext-pack
  - wget
apt_debs:
  - https://zoom.us/client/latest/zoom_amd64.deb
snap_pkgs:
  - code
  - dbeaver-ce
  - drawio
  - gitkraken
  - insomnia
  - rocketchat-desktop
  - spotify
pip_install_packages:
  - name: docker
  - name: virtualenvwrapper
users:
  - name: "{{ username }}"
    groups: "sudo, docker"
ohmyzsh_users:
  - username: "{{ username }}"
    usergroup: "{{ username }}"
    home: "{{ home }}"
config_contents:
  - name: virtualenvwrapper
    path: "{{ profile_file }}"
    block: |
      export WORKON_HOME={{ virtualenv_folder }}
      export PROJECT_HOME={{ projects_folder }}
